src/views/Recover.js
These are the front end changes, to fix account recovery.
=> #339: Fix account recovery

src/components/SubmissionBox.js
Closes #342 
Extracting first sentence for submission for description now also removes any null characters from the string (if present).
=> Adding an extra removal of null character for edge case

src/components/simple-react-footer/SimpleReactFooter.js, src/views/Register.js
(Fix is already up, because it had to be tested with the production Nginx configuration. Hence, this can wait til Monday.)
=> #345: Fix MetriqTermsofUse route

src/views/Task.js
=> #348: Link to child tasks

src/views/Task.js
Show SOTA chart if at least 3 data points, rather than 4.
=> 3 data point threshold for charts

src/App.css, src/App.js, src/components/simple-react-footer/SimpleReactFooter.js, src/components/simple-react-footer/SimpleReactFooter.sass, src/views/Home.js
I'm beginning to experiment with Kass Yassin's re-skinning design for Metriq. Here are rounded `SubmissionBox` elements, from the CSS in his mockup:
=> Make SubmissionBox rounded

src/App.css, src/components/SubmissionBox.js, src/components/simple-react-footer/SimpleReactFooter.js
Per Kass' re-skinning design suggestions, this reorganizes the `SubmissionBox` component to place certain text and controls in a "social media row."
=> SubmissionBox "social media row"

src/MainRouter.js, src/components/AuthNavRight.js, src/views/Password.js, src/views/Profile.js
These are the front end changes for #338, to let members change their passwords.
=> #338: Let members change passwords

src/views/Methods.js, src/views/Tasks.js
Per #254, task and method index sorting now uses a secondary alphabetical sort.
=> #254: Alphabetical secondary sorting

src/views/Submission.js
=> #163: Add username and date to submission

package-lock.json, src/components/MainNavbar.js, src/views/AddSubmission.js, src/views/Delete.js, src/views/Home.js, src/views/LogIn.js, src/views/Methods.js, src/views/Password.js, src/views/Profile.js, src/views/Recover.js, src/views/Register.js, src/views/Submissions.js, src/views/Tags.js, src/views/Tasks.js, src/views/Token.js
Per #387 and IQT feedback, headings should be made sequential. This doesn't fix all instances of header ordering, depending on React.js component reuse, but it fixes many of them.
=> #387: Make headings sequential

src/components/SubmissionBox.js, src/views/Submission.js
=> Consistency for social icons

src/App.css, src/components/SubmissionScroll.js
This adds a predictive text based filter to the sorted submission lists.
=> #396: Submission search

src/views/Partners.js
Partners page now include just UF and IQT.
=> Adapting partners page to include UF and IQT

src/MainRouter.js, src/components/SubmissionBox.js, src/components/SubmissionScroll.js, src/views/SubmissionsPublic.js
This adds a user filter route, for submission box views, per #406.
=> #406: User submission view front end

src/components/FormFieldSelectRow.js, src/views/Submission.js
=> #378: Disable top select for modal creation dialog

package-lock.json, package.json, src/views/Task.js
=> Adding share buttons for task.

public/index.html
Closes #269 
Writing inline description text like
```
When \(a \ne 0\), there are two solutions to \(ax^2 + bx + c = 0\).
```
Will render as
=> Adding mathjax.

src/views/Profile.js, src/views/Register.js
Closes: #386 
Depends on: https://github.com/unitaryfund/metriq-api/compare/414_initial_migration?expand=1
=> Adding ability to display and register with affiliation.

src/views/Submission.js
This alphabetically sorts method/task drop-down selections, per #419.
=> #419: Sort tasks/methods dropdowns

src/views/Profile.js, src/views/Task.js
This PR lets users edit their affiliation in the user profile view, completing #386.
=> #386: Edit user profile

src/App.css, src/views/Partners.js
=> Adding column spacing between logos.

src/App.css
=> Allowing description boxes to scale both vertically and horizontally.

src/components/CategoryItemBox.js, src/components/FormFieldTypeaheadRow.js, src/views/Method.js, src/views/Methods.js, src/views/Tasks.js
Continuing with #411, this PR applies previously reviewed UI to the task/method index views, and it adds a flattened hierarchy search filter to both views.
=> #411: Task/method index view UI and search

src/components/FormFieldSelectRow.js, src/views/Method.js, src/views/Submission.js, src/views/Task.js
To prevent members from creating new top-level task topics, all that's needed is to _require_ that any new task is a child of some other task.
=> #411: Mandatory task parent

src/views/Submission.js
All task and method selection drop-downs should be sorted alphabetically.
=> Sort all task and method drop-downs

src/App.css
=> Fixing logos going off-screen on mobile.

src/components/SubmissionBox.js, src/views/Home.js
This is the front-end for issue #217, to show tag lists for submission boxes.
=> #217: Submission tag lists (front-end)

src/App.js
=> Updating copyright.

src/views/Submission.js
Closes #249 
Adding image to submission view:
=> Adding image to submission view.

src/components/CategoryItemBox.js, src/views/Method.js, src/views/Task.js
After discussing the intent of #258 with Nathan, we determined that the "tasks" view basically already would be state-of-the-art views in themselves, except that there is no indication as to the size of the data under a given task. This PR addresses #258 by reporting and sorting by result count in child tasks.
=> #258: Highlight results count in task index and detail views

package-lock.json, package.json, src/components/SotaChart.js, src/views/Submission.js
We haven't yet determined how and under what circumstances we will display these on state-of-the-art charts. However, we now collect optional **standard error** and **sample size** fields for all **results**.
=> #505: Results confidence intervals

src/views/About.js
=> Updating 'about' page as suggested.

src/MainRouter.js, src/components/MainNavLeft.js, src/views/About.js, src/views/UserGuidelines.js
This adds the User Guidelines document view to Metriq.
=> User guidelines

src/views/Submission.js
Good catch! It's probably obvious why this is the problem with #551.
=> #551: Fix check for nonzero tag count

src/views/About.js
=> Adding space to "About"

src/views/Submission.js
=> Adding descriptor names to tasks, methods, platforms, tags, results.

src/components/Commento.js, src/views/Submission.js
This is actually the entire Commento integration, believe it or not.
=> #501: Add commento

src/views/UserGuidelines.js
=> Updating tags description in user guidelines.

src/views/Method.js, src/views/Task.js
Per #501, this PR allows comments on methods/tasks.
@nathanshammah @willzeng Do we want comments on platforms, as well? It just occurred to me, but we didn't discuss it, to my recollection.
=> #501: Task/method comments sections

src/components/Commento.js, src/components/SotaChart.js, src/views/Task.js, src/views/UserGuidelines.js
=> Front end for platform names in charts

package-lock.json, src/App.css, src/views/Methods.js, src/views/Platforms.js, src/views/Tags.js, src/views/Tasks.js
=> Adding centering to tabs in tasks, method, platforms, and tags.

src/views/Profile.js, src/views/Register.js
Related: https://github.com/unitaryfund/metriq-api/pull/194
=> Adding name field.

src/components/FormFieldAlertRow.js, src/components/FormFieldRow.js, src/views/Submission.js
This addresses #612, by fixing population of fields in the submission detail modal.
=> #612: Fix submission detail edit modal description field population

package-lock.json, src/MainRouter.js, src/views/Home.js
This addresses #618, by connecting homepage sorting tab choice to the route definition.
=> #618: Retain homepage sorting tab choice, on back button navigation

src/MainRouter.js, src/components/FormFieldAlertRow.js, src/components/FormFieldSelectRow.js, src/views/Home.js
Per #618, I forgot to handle the same tab navigation cases for tag view mode of the homepage view.
=> #618: Tag tab navigation

src/views/Submission.js
=> Updating link glyph to more appropriate link icon.

src/components/CategoryScroll.js, src/components/FormFieldRow.js, src/components/FormFieldTypeaheadRow.js, src/components/MainNavRight.js, src/components/ResultsAddModal.js, src/components/ResultsTable.js, src/components/SubmissionRefsAddModal.js, src/components/SubmissionScroll.js, src/views/Home.js
This is a feature of React.js that is new to me: if a view component _might_ not be rendered initially or at all, depending on `this.state`, then it is possible to wait to "lazy load" it, until the component is actually demanded. All lazy-loaded components must also be nested at some level under at least one `<Suspense>` tag. If done right, this can decrease page loading times.
@vprusso I know you're still on vacation with the family, so I'm just tagging you FYI. Enjoy your trip, I'll self-review, and I'll talk with you soon!
=> #657: Lighthouse suggests React.Lazy loading

src/App.css, src/MainRouter.js, src/components/FormFieldTypeaheadRow.js, src/components/MainNavLeft.js, src/components/SotaChart.js, src/views/AddSubmission.js, src/views/Home.js, src/views/Methods.js, src/views/Platforms.js, src/views/Task.js, src/views/Tasks.js
This addresses #668 and #669, to make the Tasks page the new homepage. (The old homepage has been maintained as a new "Submissions" navigation menu item, for those who would still like to browse the old-style homepage.)
@vprusso I'm about to have lunch, so I'm assigning review to you on the small chance that you see this before I'm done eating and publish, but, as you're on vacation, it's not strictly necessary. I'll self-review, in that case.
=> Make Tasks homepage

coming_soon.html, src/App.css, src/components/simple-react-footer/SimpleReactFooter.sass, src/index.css
- Arial sans-serif [appears to be](https://www.w3schools.com/cssref/css_websafe_fonts.asp#:~:text=Best%20Web%20Safe%20Fonts%20for%20HTML%20and%20CSS&text=Helvetica%20(sans%2Dserif),Times%20New%20Roman%20(serif)) a good web-safe font. Made this uniform across the entire website.
- `<h3>` tags are the lowest any section goes at most. Furthermore, it's only used sparingly and typically the deepest nesting is only to `<h2>`.
=> Updating text regularization.

package-lock.json, package.json, src/index.js
Closes: #661 
As discussed, added the [npm cookie policy package](https://www.npmjs.com/package/react-cookie-consent). 
Not entirely sure if where I placed it makes sense, but it does pop up and work. If you think it should go somewhere else, let me know.
=> Adding simple cookie policy accept

package-lock.json, package.json, src/components/ViewSubHeader.js, src/index.js, src/views/AddSubmission.js, src/views/Methods.js, src/views/Platforms.js, src/views/Tags.js, src/views/Tasks.js
Closes: #658 
Adding a one-sentence description for each menu item.
=> Adding taxonomical subheading

src/components/AnonNavRight.js, src/components/AuthNavRight.js
=> Adding metriqinfo twitter icon in the top right.

src/components/AnonNavRight.js, src/components/AuthNavRight.js, src/components/simple-react-footer/SimpleReactFooter.js
=> Updating styling of Mailchimp button.

src/components/SubscriptionButton.js, src/index.js, src/views/AddSubmission.js, src/views/Delete.js, src/views/Method.js, src/views/Platform.js, src/views/Profile.js, src/views/Submission.js, src/views/Task.js
This is the front end PR for member self-curated taxonomy item subscriptions.
=> Member subscriptions

src/views/EditDetails.js, src/views/Profile.js, src/views/Register.js
This addresses #677. Twitter handles are optionally collected for member profiles. If the user provides their Twitter handle, then the MetriqInfo bot tweets at them, whenever the bot tweets one of the member's submissions.
=> #677: Twitter handles

package-lock.json, package.json, src/components/ResultsTable.js, src/components/SortingTable, src/components/SortingTable.js, src/views/Method.js, src/views/Platform.js, src/views/Submission.js, src/views/Task.js
Per #703, this PR adds a custom `<SortingTable>` component, which sorts alphabetically, ascending or descending, when column names are clicked. This also allows us to remove the project dependency on `rc-table`.
=> #703: SortingTable component

src/components/ResultsAddModal.js, src/views/Submission.js
Per issue #707, this PR adds a delete button to the results editing modal, for convenience.
=> #707: Result modal delete button

src/views/LogIn.js, src/views/Submission.js
Per issue #709, unhelpful button text has been changed (only).
=> #709: Fix unhelpful button text

src/components/ResultsAddModal.js, src/views/Submission.js
=> #720: Add 'publish' button to submission detail view

src/views/Submission.js
=> Clicking submission image redirects to submission URL

src/components/SotaChart.js, src/views/Task.js, src/views/Tasks.js
This adds an option to choose the base of logarithmic scaling. Adding that option, we also reduce the width of the logarithmic on/off checkbox column.
=> #745: Add log base option (and shrink checkbox column)

src/App.css, src/views/About.js, src/views/FAQ.js
=> Adding YouTube videos to FAQ and About pages.

src/components/SubmissionRefsAddModal.js
This fixes the issues we saw at the last Metriq Weekly Jam Session, with predictive text inputs for task/method/platform keys on the submission detail view.
=> Fix autocomplete validation

src/views/Submission.js
=> #760: Remove text confirmation from submission publishing

src/views/Tasks.js
=> Top Submitters leader board front end

src/components/ResultsAddModal.js, src/components/ResultsTable.js, src/components/SotaChart.js, src/components/ValidationRegex.js, src/views/Task.js
=> #765: Qubit count and circuit depth result metadata

src/components/SortingTable.js, src/views/Platform.js, src/views/Submission.js
(Per #764, so Platform submissions will display)
=> #764: Fix SortingTable props update 

src/components/SotaChart.js, src/views/AddSubmission.js, src/views/Task.js, src/views/Tasks.js
(Per #744, also with a back end PR)
=> #744: arXiv label on task chart

src/views/FAQ.js
=> #636: Updating FAQ to include information on overlapping result schema information

src/components/ResultsAddModal.js, src/components/SortingTable.js, src/components/SotaChart.js, src/components/ViewSubSubHeader.js, src/views/AddSubmission.js, src/views/Platform.js, src/views/Submission.js, src/views/Task.js, src/views/Tasks.js
=> #379: Updating language for including date in submission

src/views/Task.js
=> #770: Export to csv extension instead of txt.

src/views/FAQ.js
=> #632: Adding clarification on task hierarchy.

src/views/AddSubmission.js, src/views/FAQ.js, src/views/Submission.js
(Per issue #264. Also, I ran the code formatter, hence the changes to your text update, Vincent.)
=> #264: Add new URLs to submission

src/components/SotaChart.js
arXiv labels can be printed on the task plots, for SOTA points. (Printing them for every point would be illegible, per #744.)
=> #744: arXiv SOTA labels

src/App.css, src/components/SotaChart.js
Per #755, task chart text has been optimized for readability, via contrast, font size, and font weight.
=> #775: Chart text readability

src/views/Tasks.js
Per #785, the homepage has been "restyled" for usability and clarity. This includes a one-sentence description of "how to get going," at the top of the homepage.
=> #785: Restyle homepage

src/components/SotaChart.js
Per #794, arXiv IDs have been shortened, on task charts.
=> #794: Shorten arXiv ID on task charts

src/components/CategoryItemBox.js, src/components/FormFieldRow.js, src/components/ValidationRegex.js, src/views/AddSubmission.js
Per #645, we can make sure users know what fields are required ahead of time by triggering the red "validator" text on view load.
=> #645: Indicate submission required fields

src/App.css, src/components/FormFieldTypeaheadRow.js, src/components/MainNavLeft.js, src/components/SubmissionScroll.js, src/views/Methods.js, src/views/Platforms.js, src/views/Tasks.js
Per #786, this is the front end for a general filter bar. (There is also a corresponding back end update.)
=> #786 general filter bar

src/views/Submission.js
Per #380, we can pull in author names from arXiv, like we do for the results date.
=> #380: Get authors from arXiv

src/components/FormFieldTypeaheadRow.js, src/components/MainNavLeft.js
Per #814, the search bar label has been removed, the text input has been made wider, and an input hint has been added.
=> #814 improve search bar

src/App.css, src/MainRouter.js, src/components/CategoryItemBox.js, src/components/MainNavLeft.js, src/views/Qedc.js, src/views/Tasks.js
Per #832, this PR adds a view that highlights QED-C benchmark results.
=> QED-C view

src/components/FormFieldRow.js, src/views/Method.js, src/views/Task.js, src/views/Tasks.js
Per #834, this PR allows users to edit task and method names (except for top-level tasks).
=> #834: Option to edit task/method name

src/components/SotaChart.js, src/views/Task.js
Per #838, clicking a data point on a chart now links to the corresponding submission.
=> #838: Link to submission when clicking on chart data point

src/views/Home.js
Per #839, hide any entries in the top submitters with 0 submissions, (and hide the tab, if all three top submitters have 0 submissions).
=> #839: Don't show 0 counts for top submitters

src/views/Tasks.js
=> remove unitaryHACK notice

src/App.css, src/components/SortingTable.js, src/components/SotaChart.js, src/components/SotaControlRow.js, src/components/TopSubmitters.js, src/config.js, src/views/Task.js
This implements Frances' mockup.
=> Task view redesign

src/views/Platforms.js
Between this and the back end, this is presents architectures and providers to users.
=> Front end for architecture/provider counts

src/views/Sota.js
=> Fixing minor misspelling.

src/views/AddSubmission.js
=> Prepopulate result date when add submission

src/components/FeaturedTask.js, src/components/QuantumLandscapeChart.js, src/views/AddSubmission.js, src/viz-style.css
These changes are per the suggestions of @willzeng.
=> Progress chart updates

src/components/QuantumLandscapeChart.js, src/components/SotaChart.js, src/views/Home.js
=> No need for Charts.js error bars

src/App.js
Updates the copyright notice in the footer to read "... - 2024."
=> Update Copyright Year - 2024

src/progress.csv
Adding these from https://arxiv.org/abs/2503.02984 or your review @WrathfulSpatula
=> Add new ECC results to progress chart

src/progress.csv
Add resource estimates from https://arxiv.org/abs/2502.15882
For your review @WrathfulSpatula
=> new resource estimates for ground state

package-lock.json, src/components/MainNavLeft.js, src/components/QuantumVolumeChart.js, src/components/SubmissionRefsAddModal.js
This fixes many various issues with the presentation of task data on charts, particularly the bar charts.
=> Chart issues

package-lock.json, package.json, src/components/SortFunctions.js, src/views/Methods.js
=> fix: sort methods alphabetically works.

src/components/AggregatedMetricsTable.js, src/views/Trends.js
Resolves #982 
Screenshot shows the table on local with test data.
=> Show aggregated metriq-gym table in trends page

src/components/QuantumVolumeChart.js
Does what the screenshot shows
=> Prettier y-axis labels in QV-style charts

src/components/TopSubmitters.js
=> Fix username links from submissions page

src/MainRouter.js, src/components/AuthNavRight.js, src/views/MyFollows.js
=> Add follows page

.gitignore
=> git ignore build folder
