unitaryfoundation/metriq-app

- src/views/Tasks.js
Per #347, the first part is to remove the existing network graph, which seems to be confusing and unhelpful to users. More work will follow, to replace it.
> #347: Remove network graph

- src/App.css
- src/components/FormFieldRow.js
- src/views/Submission.js
Per #361, these are the front end changes to let users edit results, without deleting them and adding them a second time.
> #361: Let members edit results

- src/components/SubmissionBox.js
As a first step in development, for expanded "social credit" and social media functionality, we show the submitting username for each `SubmissionBox`.
> #368: Show submitting username in SubmissionBox

- src/components/AnonNavRight.js
- src/components/AuthNavRight.js
(Per #354...) It's unfortunate that our primary issue board is not in the same repo as our parent project, but I think I agree with Nathan that it makes more sense to direct social links to the primary issues board. We're somewhat stuck with this being "backwards" like this, but users are probably more frequently going to be interested in opening issue tickets than in cloning the 3 repos.
> #354: Replace social link to metriq-api repo with metriq-app repo

- src/MainRouter.js
- src/views/AddSubmission.js
This closes #376. If an anonymous user directly navigates to the URL to add a new submission, they are redirected to the login view instead, (which will next redirect them back to the new submission view after they log in).
> #376: Redirect AddSubmission to login if anonymous

- src/views/Method.js
- src/views/Submission.js
- src/views/Task.js
Closes #425 
- Adding FB/Twitter share buttons to "method" and "submission" pages
- Improving the "look" of the social share buttons.
> Adding share buttons to method, submission, and task.

- src/views/Method.js
- src/views/Submission.js
- src/views/Task.js
This makes methods into a hierarchy equivalent to tasks, restricts method and task index views to top level, and gives administrators the option to hide SOTA comparison charts for tasks. These changes let administrators use top level tasks and methods in the database as very general categories, (without displaying confusing or poorly motivated top level task category SOTA comparisons).
> #411: Top level topics

- src/components/FormFieldSelectRow.js
- src/views/Method.js
- src/views/Submission.js
- src/views/Task.js
If one checks the browser console, this fixes two warnings/error in the app: buttons cannot be nested within buttons, and `value` property on `<select>` should be used instead of `selected` property on nested `<option>` tags.
> Fix React.js warnings

- src/components/SubmissionBox.js
This closes #412, by clearly visually indicating links in `SubmissionBox`.
> #412: Clear link for user submissions

- src/App.css
- src/views/Task.js
This addressed #460, by hiding illegible charts in narrow mobile views and replacing them with a message to let the user know they should try landscape view instead, which will usually immediately restore the chart.
> #460: Hide chart if screen is too narrow

- src/App.css
- src/components/CategoryItemBox.js
This addresses #451, by using React.js to dynamically reformat the `CategoryItemBox` DOM when the "description" field is empty.
> #451: Center CategoryItemBox text when description is blank

- src/views/Submission.js
Per #438, this makes all task/method creation fields optional except "name," (and parent category, just for tasks).
> #438: All task/method fields optional except name (and task parent)

- src/components/FormFieldRow.js
- src/views/AddSubmission.js
This adds a submission description placeholder hint, per #271.
@crazy4pi314 Looking at the particular text of the placeholder that I give here, is there anything you think we should add? I think an appropriate description could follow any style guide for a research article abstract, personally.
> #271: Submission description placeholder

- src/views/Methods.js
This fixes the bug from #502, which caused a white screen to display when the methods filter was used.
> #502: Fix method filter white screen bug

- src/views/Submission.js
Per #505, the notes on "standard error" have been updated to make its usage and theoretical usage transparent.
@crazy4pi314, If you look at the exact text of the tool-tips, I feel confident saying exactly this:
> Confidence intervals will be calculated as ± standard error times z-score, if you report a standard error. This is self-consistent if your statistics are Gaussian or Poisson, for example, over a linear scale of the metric. (If Gaussian or Poisson statistics emerge over a different, non-linear scale of the metric, consider reporting your metric value with rescaled units.)
To the best of my knowledge ever working in data science, this is almost a tautological statement by _definition of "standard error,"_ (at least for two-tailed distributions, I think,) even if different …
> #505: Explain usage of standard error to members

- src/components/FormFieldSelectRow.js
- src/views/Submission.js
Per #523, this makes top level categories a visually distinct `<optgroup>` among tasks.
> #523: Top level category optgroup

- src/config.js
- src/views/Method.js
- src/views/Platform.js
- src/views/Submission.js
- src/views/Task.js
Per #527, linking to any hypothetically valid page URL on wiki.metriq.info will land a user either on an existing page or a dialog to create the new page URL.
> #527: Links to hypothetical pages let users create them

- src/views/Submission.js
Per #538, it was difficult to read multiple tags in the submission detail view, without a separator.
> #538: Add tag separator in submission detail view

- src/views/Submission.js
Per #550, about alphabetization, there was a redundant API call to retrieve platforms after the sorting step had already taken place. This removes it, which should also slightly reduce loading time for certain view data.
> #550: Remove redundant API call, for platform names

- src/views/Submission.js
In submission detail view, when editing a result, we need to compare the result DTO "row" with the set of all results DTOs and populate the modal view. However, the code we use to do this edits the row in-place, by reference. If we clone the row (by copying its values) before editing it, we can still make the necessary comparisons and updates, but the original row is left unaltered, in-place.
> #556: Fix edit 'flicker'

- src/components/CategoryItemBox.js
Per #580, this will split `<CategoryItemBox>` into two rows, with title and description on the first row, and stats on the second row.
> #580: Put <CategoryItemBox> on two rows, on mobile

- src/components/SotaChartMobile.js
- src/views/Task.js
We _cannot_ display the entire information of the desktop SOTA charts will the same detail in mobile _portrait_ view, nor should we try. However, we _can_ strip the chart of all data point labels and rely on the interactive tooltips to communicate the same information, in so narrow of a space.
I suspect we'll iterate on this again, but it's a good step in the right direction. We'll let the team try it, and they can follow up with additional feedback on #578.
> #578: Mobile portrait view charts

- src/components/SotaChart.js
- src/components/SotaChartMobile.js
Per issue #560, 10 ticks at most are now shown for chart x axes.
> #560: Reduce chart ticks

- src/App.css
- src/components/simple-react-footer/SimpleReactFooter.js
People continue to have issues with the sticky footer. Several steps have been taken to alleviate the issue:
1. The empty space at the bottom of all pages has been increased significantly, to completely avoid overlap between footer and content.
2. The delay before the footer reacts to hover has been increased from 1/3 of a second to 1/2 of a second.
3. The footer now responds to viewport window resizing, (but it has to return to the "neutral" position of pop-up, first, to measure its own height and position, before collapsing again).
Please consider that we might not want a sticky footer _at all_. We have conflicting design requirements, here, in terms of _why_ we want the sticky footer in the first place (i.e., always occupy a portion of the screen with legal and social information) and …
> #529: Sticky footer fixes

- src/components/SotaChart.js
- src/components/SotaChartMobile.js
Per #578, charts have been made more readable. We use a (slightly) smaller font, center-align labels, and modify the SOTA line calculation slightly to only include the _first data point in time_ to reach a SOTA result.
For the SOTA calculation, firstly, this is conceptually more correct: for two or more identical results at SOTA level, SOTA was established for the _earliest_ one. However, incidentally and conveniently, this makes us less likely to be forced to render two SOTA labels at the exact same height on the graph and close in time, improving the readability of the charts.
.
> #578: For charts, smaller fonts, center-align text, SOTA is strictly improvement

- src/MainRouter.js
- src/components/CategoryItemBox.js
- src/views/LogIn.js
- src/views/Method.js
- src/views/Platform.js
- src/views/Register.js
- src/views/Submission.js
- src/views/Task.js
For #558, you're aware from the research on the issue that you shared with me that `react-router` has a "stack" of views that the user has navigated since arriving on a URL with the `<MainRouter>`. Within the context of `<MainRouter>`, ("any view inside its opening and closing tags," basically,) Clicking `<Link>` tags and triggering programmatic manipulation of the router history will redirect the user to other views, and push their old views on the "stack."
We had "abused" this functionality, previously, in part because I personally didn't see an easy way to make it work with our `<Table>` component dependency. It turns out, it's not a perfectly clean solution, but we can append `this.props` from the containing component class to table data rows, to access the router history within …
> #558: Use react-router consistently throughout app

- src/components/SotaChart.js
- src/components/SotaChartMobile.js
- src/views/AddSubmission.js
Per #461, artificial time stamp information, below the date level, has been removed from task charts.
Also, we noted in passing that content URL should be collected on the top line of the submission workflow, since this automatically populates the title and description.
> #461: Chart date formats

- src/App.css
- src/components/SotaChartMobile.js
For mobile view charts, this enables Charts.js' `responsive` option and sets a minimum chart height.
> #460: 'responsive' Charts.js option and 'min-height' styling

- src/components/FormFieldRow.js
- src/components/FormFieldSelectRow.js
- src/views/Submission.js
Turns out that our issue for #613 specifically happens with only the "Applications" task category, if and when the selection is left default by intention. This fixes it, though.
> #613: Populate default parentTask ID, to create new tasks

- src/components/ValidationRegex.js
- src/views/AddSubmission.js
- src/views/Forgot.js
- src/views/LogIn.js
- src/views/Password.js
- src/views/Platform.js
- src/views/Recover.js
- src/views/Submission.js
Per #621, by centralizing the definition of our regular expressions for form field input validation, we ensure that the same intended validation conditions are maintained across all instances of usage. (Also, `Regex()` initialization and use can be expensive, and this design might improve performance in certain cases of usage.)
> #621: Centralize Regex definitions

- src/MainRouter.js
- src/components/AuthNavRight.js
- src/views/MySubmissions.js
-  File Submissions.js changed to MySubmissions.js 
- export class in MySubmissions.js changed to `MySubmissions`
- navbar points to `/MySubmissions`
- In MainRouter.js all instances of `Submissions` have been changed to `MySubmissions`
> Submissions changed to MySubmissions

- src/components/FormFieldTypeaheadRow.js
- src/components/SubmissionRefsAddModal.js
- src/views/AddSubmission.js
If text entered in the "typeahead" to add a taxonomy reference isn't found as an option, so the user clicks "New" to add it, then the same text is used to prepopulate the "New" option modal.
> #728: Prepopulate 'new' modal from typeahead

- src/components/FormFieldTypeaheadRow.js
- src/components/SubmissionRefsAddModal.js
- src/views/Task.js
This adds a "type-ahead" components for submission reference (i.e. task/method/platform) parents.
> #742: Typeahead for parent refs

- src/components/SubmissionRefsAddModal.js
- src/views/Submission.js
This closes #747, by removing top-level tasks as an option for submission references.
> #747: No top level task keys in modal

- src/views/About.js
- src/views/AddSubmission.js
- src/views/FAQ.js
Per #751, there's a much simpler solution than retrofitting the "Add Submission" workflow to fill with the old draft: by the same logic that would _detect_ an existing draft, just give the user the option to automatically redirect to the draft page, if it exists.
> #751: Detect and redirect users to existing submission drafts

- src/components/ResultsAddModal.js
Per issue #715, this adds a button that allows users to submit a result (under a submission) while keeping the result-adding modal open and populated with the previous data, making it easier to add many semi-repetitive results.
> #715: 'Submit and Repeat' for results entry

- src/views/Register.js
Per issue #781, after a user had an issue with signup, the Twitter handle field now accepts inputs with and without a leading `@` character.
> #781: Accept Twitter handles with or without '@' character

- src/views/Submission.js
Per #744, the submission arXiv ID is now displayed in the submission detail view, if it's available.
> #774: Display arXiv ID in submission detail view

- src/components/CategoryItemBox.js
Per issue #783, this PR allows users to follow taxonomy items from index views. (There is also a corresponding back end PR.)
> #783: Front end to follow taxonomy from index views

- src/components/ResultsAddModal.js
- src/views/Submission.js
Per #793, it turns out that we never collect the arXiv publication date from users, but we can grab it directly from the arXiv API, to prepopulate the result entry modal.
> #793: Prepopulate result date (from arXiv API)

- src/MainRouter.js
- src/views/Tasks.js
Per #803, @nathanshammah requested that we add the top 3 "trending"/"popular"/"latest" submissions to the homepage.
This works for the homepage, (proper,) but the design is becoming extremely "busy" as the _tasks_ page. Hence, when the user clicks the "Tasks" menu item, they see the same view _without_ top submissions and top submitters, in this PR.
> #803: Homepage 'Top Submissions'

- src/components/SotaChart.js
Per #795, we can fix out-of-bounds labels on the charts with additional padding. (I have checked that the mobile view is not broken by the change.)
> #795: Add chart padding

- src/App.css
Per #646, modal form field labels have been centered to match their hover tool tips.
> #646: Center form labels (for tooltip styling)

- src/App.css
- src/components/MainNavbar.js
Per #642, to make the design less crowded, we hide the header text in mobile portrait view.
> #642: Hide header on mobile portrait view.

- src/components/ResultsAddModal.js
- src/components/ResultsTable.js
- src/components/SubmissionRefsAddModal.js
- src/components/ValidationRegex.js
Per #822, this fixes the interoperability of predictive-text copy-over, with new-taxonomy-item modal validation. (This was my fault, originally, @WrathfulSpatula.)
> #822: Validate initially, when copying predictive text to modal

- src/components/MainNavLeft.js
- src/components/SotaChart.js
- src/components/SubmissionRefsAddModal.js
Per #778, previously, when all task metric data was from the same date, every point in the scatter plot had the exact same x-axis value, which was unhelpful. Alternatively, these points are now presented as separate bars in a bar chart, whenever this case arises.
> #778: Bar chart for single date

- src/components/ResultsTable.js
Per #809, this turns task/method/platform fields in results tables into links to the appropriate taxonomy item detail views.
> #809: Link to task/method/platform in results table

- src/progress.csv
Remove scientific notation from data, for easier parsing in the quantum landscape chart.
> remove scientific notation

- src/components/MainSearchBar.js
closes #851
Please find the video attached where we can see the safari page hung with the metriq-api logs. Can be replicated by running the metriq-app locally with metriq-api and force reloading the page in Safari version 17.2.1
https://github.com/unitaryfund/metriq-app/assets/19835609/584db49f-ee32-41b4-86e9-e0ee7e1021a6
The metriq-app frontend in safari is performing multiple unnecessarily metriq-api server REST APIs in an infinite loop when refreshing the page. Then the page hangs. This is because the useEffect hook is running multiple times because it's watching too many dependencies i.e it's watching all the state variables and their setters. This creates a race condition to update the dependencies of useEffect.
We want the useEffect hook should only be dependent on allNames.length …
> Fix race condition causing Safari browser to hang

- src/components/FeaturedTask.js
In this pull request, I have addressed the issue by ensuring that LaTeX is properly rendered in the descriptions of featured tasks item listing on the homepage as it happens on other sections. Specifically, any text elements surrounded by the $ delimiters are now correctly processed and displayed as LaTeX. [Unitary Hack 2024]
> Markdown rendering on homepage

- src/components/QuantumLandscapeChart.js
Per request by @willzeng, the toggles have been changed to a radio-button group, in the Progress chart.
> Radio buttons in progress chart

- package-lock.json
- package.json
- src/components/MainNavLeft.js
- src/components/QuantumLandscapeChart.js
- src/components/SotaChart.js
- src/views/Home.js
See my note on #914. This featured task chart display bug is significantly trickier than I expected:
- The bug is not limited to coherence gain, if various tasks are switched into the featured task slot, but not all of them.
- It also doesn't necessarily appear to be connected to invalid result data.
- It raises no JavaScript or REST API error in the browser debugger.
I really don't know what the issue is, here! The long-term solution is to completely remove our dependence on Chart.js, I honestly think, as we've moved towards in 2024.
I think a temporary fix might be simply to change up the feature tasks a bit: I don't think it's less appropriate, particularly just as a temporary measure, to highlight single-qubit T1 relaxation times.
I am continuing to diagnose the issue or, ultimately, …
> Minor bug fixes

- package-lock.json
- src/components/QuantumVolumeChart.js
In Chrome, the state-of-the-art line was rendered incorrectly on charts like Quantum Volume.
As can be seen in the PR, this is _purely_ a bug in _Chrome._ By resorting to _manual_ date parsing and sorting, we work around it.
> Work-around for bug in Chrome Array.prototype.sort()

- .github/workflows/deploy-qa.yml
- src/App.js
The PR will automatically calculate the to-year in the copyright notice, so that it does not need to be updated in the future. It also adds a scheduled deployment to Github Actions on 1 January so the copyright notice is immediately updated at the  start of the year.
> Automate Copyright Updates

- package-lock.json
- src/components/SubmissionRefsAddModal.js
Fixes #957. This is as far as I got on the night of 2025-03-26, and it's self-contained, so I wanted it be reviewed as a granular change, after a one-off commit to `main` to fix the refresh loop problem I introduced in wrapping D3.js code for React.js that we contracted for that was _good,_ even though it was completely naive to React (as we knew and agreed to).
I have to snark in defense of the commit message and this "code debt" (i.e. "rug-pull"), to give my team a window into what career "full-stack Web development" actually entails, boots-on-the-ground: yes, **Facebook** (and maybe even **Zuck'** personally, who knows) hypothetically notices one day, we can "optimize" our library, central to the modern Web, to not update the "MVC" "view" if user code assigns the self-same object back …
> Fix add-submission-reference modal (MVC) model synchronization

- src/components/QuantumLandscapeChart.js
- src/components/QuantumVolumeChart.js
Replaces hardcoded external URLs with relative internal URLs. 
Currently, when running it locally, those links bring the page out of the localhost environment. 
This change also adds the flexibility of deploying Metriq to a different domain. 
Tested by clicking on the dots of the QV chart on the Trends page
> Use app's routing system for URLs

- src/views/AddSubmission.js
It's a complementary PR to https://github.com/unitaryfoundation/metriq-api/pull/237
The new library used to parse html metadata doesn't fetch images url from the page. Not an important feature imho, and we can re-add it in the future.
> Remove autofilling of submission thumbnail url

- src/components/QuantumVolumeChart.js
Axis labelling fixed/adapted from 
to:
> fix: Fixing y-axis legend numbering for d3

- src/progress.csv
- Removed two recently added results for the progress chart that were keyed in using physical quibts (instead of logical qubits). 
Reverting #1007
> chore: removed logical vs. physical qubit results from progress chart

- src/components/QuantumLandscapeChart.js
- Changing y-axis label from "Qubits" to "Logical Qubits" for clarity.
> chore: clarify y-axis for landscape chart

- src/MainRouter.js
- src/components/MainNavLeft.js
- src/views/MetriqGym.js
- src/views/Trends.js
Simple redesign, moving the metriq-gym table to a new page with a dedicated tab link in the navigation bar.
> New metriq-gym tab in navigation bar 

- src/components/SubmissionRefsAddModal.js
When selecting an item under the "Add Task" modal (or any of the other modals in fact), the first item that is selected enables the "Submit" button (whereas before, this would have to be clicked twice to do so).
> fix: item can be added properly now under task
